### ISSUE TITLE
Can't start the local repo locally

### ISSUE THREAD

**Issue by matthieuchabert** [superfly/fly_postgres_elixir#10]
Hi 👋

I'm trying to add read replicas to my application with this library but I'm struggling to make it work locally.

I'm starting the LocalRepo in my `application.ex`.
```elixir
children = [
      # Start the RPC server
      {Fly.RPC, []},
      # Start the Ecto repository
      Homepage.LocalRepo,
      # Start the tracker after your DB.
      {Fly.Postgres.LSN.Tracker, []},
     ...
    ]
```

The LocalRepo looks like this:
```elixir
defmodule Homepage.LocalRepo do
  use Ecto.Repo,
    otp_app: :homepage,
    adapter: Ecto.Adapters.Postgres

  # Dynamically configure the database url based on runtime environment.
  def init(_type, config) do
    {:ok, Keyword.put(config, :url, Fly.Postgres.database_url())}
  end
end


defmodule Homepage.Repo do
  use Fly.Repo, local_repo: Homepage.LocalRepo
end

```

But it seems that calling `Fly.Postgres.database_url()` requires to set the variables: `PRIMARY_REGION` and `FLY_REGION`.
Which is a bit odd given that those variables are set by Fly.

If I run `mix phx.server`, I get: `(ArgumentError) could not fetch environment variable "PRIMARY_REGION" because it is not set`

I only have `config :fly_postgres, :rewrite_db_url, true` set in `runtime.exs`.

Maybe I'm missing something, do you have any suggestion ?

Thank you.

**Comment by brainlid** [comment]
Hello @matthieuchabert! Thank you for trying the library and reporting this issue. I realized that the docs on the library are lacking. It was instead documented in the community pages on Fly.io.

I will update the README! But yes, to answer you question, you should set the two ENV variables locally. For example, I use [direnv](https://direnv.net/) to help manage that for me. For local dev work, you want to mimic being the primary. So you could create an `.envrc` file with the following contents.

```
export FLY_REGION=xyz
export PRIMARY_REGION=xyz
```

This tells the app that your primary region is the same region you are running in, so it will write directly to the database.

Like in the [testing doc](https://github.com/superfly/fly_rpc_elixir/blob/main/TESTING.md), you can also execute it this way as well.

```
FLY_REGION=xyz PRIMARY_REGION=xyz iex -S mix phx.server
```

If the primary region and fly region differ, then it expects to connect to a replica DB.

Thanks for helping to identify the gap in the docs! I'll get that fixed.

**Comment by brainlid** [comment]
@matthieuchabert I added [Local Development](https://github.com/superfly/fly_rpc_elixir#local-development) sections to the README for [`fly_rpc`](https://github.com/superfly/fly_rpc_elixir) and `fly_postgres`. 

It includes the information above, but I would love your feedback on if it can be made more clear.

**Comment by matthieuchabert** [comment]
@brainlid It's very clear! Nothing to add in my opinion 🙂
