### ISSUE TITLE
Recent change in flyctl makes url rewrite unnecessary?

### ISSUE THREAD

**Issue by kkondaurov** [superfly/fly_postgres_elixir#14]
This could be a total non-issue, but I couldn't help but notice:

I recently created a multi-region PostgreSQL cluster, and apparently `fly pg attach` set the host part of the DATABASE_URL to  `top2.nearest.of.<pg app>.internal`  (as far as I understand, this was a [recent change in flyctl](https://github.com/superfly/flyctl/commit/6df49f94391f783dc5f399a629cd9e2994a3e3dd#diff-f5b7157e38e0809c6833c2e33cbc460a454c55f3c21b5be23bff99bb8a2f07b1R479)). So the way url rewrite works now, app instance in "primary" region connects to `<primary-region>.top2.nearest.of.<pg app>.internal`, and instances in other regions connect to `top1.nearest.of.top2.nearest.of.<pg app>.internal`.

Everything seems to be working fine, but I'm wondering if this new default version of DATABASE_URL makes primary/replica host rewrites unnecessary, or maybe breaks some assumption and potentially introduces a problem?

For example, I have an app with instances in `fra` and `ord`, and a pg cluster with leader and one replica in `fra` and another replica in `ord`.

Here's what the rewritten hostname resolves to for app instance in `fra` :
```
root@3871ba0f:/# dig +short aaaa fra.top2.nearest.of.redexor-pg-cluster.internal
fdaa:0:344e:a7b:23c3:0:71e1:2
fdaa:0:344e:a7b:23c6:0:71e0:2
```
the `fra` subdomain seems to have no effect (the third IP is a replica in `ord`):
```
root@3871ba0f:/# dig +short aaaa fra.top3.nearest.of.redexor-pg-cluster.internal
fdaa:0:344e:a7b:23c3:0:71e1:2
fdaa:0:344e:a7b:23c6:0:71e0:2
fdaa:0:344e:a7b:2052:0:71e2:2
```
Same machine, without the rewrite:
```
root@3871ba0f:/# dig +short aaaa top2.nearest.of.redexor-pg-cluster.internal
fdaa:0:344e:a7b:23c3:0:71e1:2
fdaa:0:344e:a7b:23c6:0:71e0:2
```

And in `ord` :
```
root@01b4e350:/# dig +short aaaa top1.nearest.of.top2.nearest.of.redexor-pg-cluster.internal
fdaa:0:344e:a7b:2052:0:71e2:2
```
(so apparently `top1.nearest.of` here - unlike `fra` - does provide additional filtering?)
and without the rewrite:
```
root@01b4e350:/# dig +short aaaa top2.nearest.of.redexor-pg-cluster.internal
fdaa:0:344e:a7b:2052:0:71e2:2
fdaa:0:344e:a7b:23c3:0:71e1:2
```

Maybe I'm missing something - I'm just exploring the fly.io platform and this library - but as far as I understand, the region name is injected into the DB url for primary app instances because we can't rely on hostnames set by older versions of flyctl (that is, `something.internal` without `top2.nearest.of`) to consistently resolve to pg instance in primary region -  but maybe with the new version, which explicitly asks for the "nearest" pg instance, we can?

And if we can't, then I guess we would need to replace `top2.nearest.of` with primary region name, rather than prepend?

**Comment by brainlid** [comment]
@kkondaurov, very good point. You are correct. It's time to re-vist the config. :slightly_smiling_face: 

We still need to know what the PRIMARY_REGION is, because we need to know when this running instance is _not_ in the primary. The reason is so the URL can be modified for the PORT. This lets us target the replica because they run on different ports. But I think that can all be done automatically without continued need for the config.

I'll look into it and test some changes. Thanks for bringing this up!

**Comment by kkondaurov** [comment]
@brainlid Thank you for this fun library!

> We still need to know what the PRIMARY_REGION is, because we need to know when this running instance is _not_ in the primary. The reason is so the URL can be modified for the PORT. This lets us target the replica because they run on different ports. But I think that can all be done automatically without continued need for the config.

Well this is very intriguing!

As far as I understand, each app instance needs not only to know if it's in the primary region, but also the specific name of that region, so that in non-primary regions `fly_rpc` would direct write queries to primary node(s), connected to cluster leader on 5432?

So... there's a way for an app instance figure this out without the setting?

I guess assuming that:
- we can rely on  `regions.appname.internal` response to always list regions in the order they were added (it looks that way, but I'm not sure),
- the PostgreSQL cluster leader is in the first region, and always stays there (does it though?),
- the app always has at least one instance in the pg leader region,

we could have each node run `:inet_res.lookup 'regions.<original db hostname>.internal', :in, :txt` and parse the result to get the primary region.

Does this make sense? Or too many/shaky assumptions and moving parts?

**Comment by brainlid** [comment]
@kkondaurov Thanks for your thoughts!

You may be right, that there is probably a way to do a DNS lookup or inquiry to find where the cluster leader is. I've just opted to go a little simpler. At least for now. 

I've been working on the library and I hope to have a new version published over the weekend. It removes the `config :fly_postgres, rewrite_db_url: true` setting and relies on the newer Fly database names with DNS resolution helpers.

**Comment by kkondaurov** [comment]
Oh sure, that was just a wild idea. Thank you again for the library!

**Comment by brainlid** [comment]
URL rewriting was completely reworked. It _should_ be working better. No config needed for prod mode to enable re-writing.

Part of 0.2 release
