### ISSUE TITLE
mix ecto.gen.migration puts migrations in priv/local

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly_postgres_elixir#15]
Renaming `MyApp.Repo` to `MyApp.Repo.Local` changed how the ecto migration generator names my migration files. I still want them named as if I'm using `MyApp.Repo`, though.

**Comment by kkondaurov** [comment]
I believe you can configure this path:
```
config :my_app, MyApp.Repo.Local,
  priv: "priv/repo"
```
Maybe this should be mentioned in README?

**Comment by brainlid** [comment]
Thanks for the recommended fix! Added to the README.
