### ISSUE TITLE
Error running migrations on version 2.0

### ISSUE THREAD

**Issue by fedeotaran** [superfly/fly_postgres_elixir#20]
Hi! :D 

I am trying to update the package to the latest version.

When I run the migrations (with an update query) using the new settings, I get the following error:

```bash
❯ MIX_ENV=test mix ecto.migrate
Compiling 1 file (.ex)

18:43:07.232 [info]  == Running 20220123222023 MyApp.Repo.Local.Migrations.AddCodeToAlbums.up/0 forward

18:43:07.236 [info]  alter table albums

18:43:07.305 [debug] QUERY OK source="albums" db=2.0ms
UPDATE "albums" AS a0 SET "code" = $1 [<<1, 127, 35, 99, 86, 236, 122, 124, 253, 61, 216, 142, 130, 189, 151, 143>>]
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 3.17) :ets.lookup(:"lsn_tracker_ets_cache_Elixir.Fly.Postgres.LSN.Tracker", :repo)
    (fly_postgres 0.2.0) lib/lsn/lsn_tracker.ex:47: Fly.Postgres.LSN.Tracker.get_repo/1
    (fly_postgres 0.2.0) lib/fly_postgres.ex:173: Fly.Postgres.__rpc_lsn__/4
    (fly_postgres 0.2.0) lib/fly_postgres.ex:150: Fly.Postgres.rpc_and_wait/4
    priv/repo/migrations/20220123222023_add_code_to_albums.exs:16: MyApp.Repo.Local.Migrations.AddCodeToAlbums.up/0
    (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:279: Ecto.Migration.Runner.perform_operation/3
    (stdlib 3.17) timer.erl:166: :timer.tc/1
    (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8
```

I don't understand why this error appears only when running migrations.
Do I have to load the app before running the migrations?

I added the following line on my `application.ex`

```elixir
children =
      [
        {Cluster.Supervisor, [topologies, [name: MyApp.ClusterSupervisor]]},
        {Fly.RPC, []},
        MyApp.Repo.Local,
        {Fly.Postgres.LSN.Tracker, repo: MyApp.Repo.Local},
       ...
      ]
```

I'm missing something?

Thanks!

**Comment by brainlid** [comment]
Thanks for reporting! I'll look into it.

**Comment by brainlid** [comment]
I was able to reproduce it. The key was doing the query in the migration. Generally a discouraged practice, but it should be supported.

**Comment by brainlid** [comment]
So here's the answer:

In your migration, directly use the local repo.


```elixir
MyApp.Repo.Local.update(...)
```

This is safe because in production, the migrations are only run in the primary region. It doesn't work to use the wrapped repo because the application hasn't been started (and shouldn't be... data structures are changing) so the Tracker process isn't started to create the ETS table.

Regarding why it's not a recommended practice and alternatives, you can read more here: https://fly.io/phoenix-files/backfilling-data/

Should be an easy fix! Hope that helps!

**Comment by brainlid** [comment]
I'll add this to the docs/readme.

**Comment by fedeotaran** [comment]
Great! this is really helpful.

We are not in production at the moment, so we will change this. But sometimes it is necessary to do this in production.

We'll make the changes and read the article! Thanks! 😄
