### ISSUE TITLE
Maybe a bug: Trying to connect to nearest.of.localhost

### ISSUE THREAD

**Issue by nicanor** [superfly/fly_postgres_elixir#21]
Hi.
We updated fly_postgres to 0.2.0 and ran into a problem.
When runing `mix ecto.reset` locally I got:

```
09:16:33.228 [error] GenServer #PID<0.436.0> terminating
** (DBConnection.ConnectionError) tcp connect (top2.nearest.of.localhost:5432): non-existing domain - :nxdomain
    (db_connection 2.4.1) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
```

The problem was that it was trying to connect to **top2.nearest.of.localhost:5432** instead of **localhost:5432**.

I made it work locally by adding an alias in /etc/hosts
```
127.0.0.1.   top2.nearest.of.localhost:5432
```

But I think this is not the expected behaviour when running the app locally. Am I right?

Please let me know if you need any more information.

**Comment by brainlid** [comment]
Correct. It should not do that. Thank you for reporting! I'll check it out.

**Comment by brainlid** [comment]
Hi @nicanor! 

I'm unable to reproduce the behavior. Do you have any other tips? It's working for me locally in dev... which is what it looks like you are doing as well. I tested it with and without PRIMARY_REGION ENV settings as well.

I tested using v0.2.1

**Comment by nicanor** [comment]
Hi, @brainlid!

Thanks for your response. I updated to v0.2.1 and the problem persists.
I have PRIMARY_REGION ENV set locally. So, I don't think it's related to that.

I think that the reason I have this problem and you don't is that we use URL notation for configuring the database. Even if we do it locally. E.g.:
```
# dev.exs

config :my_app, MyApp.Repo.Local,
  url: System.get_env("DATABASE_URL", "ecto://postgres:my_app@localhost/my_app_dev"),
  ... # Other db configurations
```

And the `[Fly.Postgres.config_repo_url()](https://github.com/superfly/fly_postgres_elixir/blob/a18d75e1ad4d924416c6ffeb3c21266cb4b3175f/lib/fly_postgres.ex#L13)` function has a case that will add "top2.nearest.of" in case it finds "url" in config.

This function even has a comment: `# :url key not found. Likely local dev/testing. Return unchanged.`
So, I think that's the problem. It relies on check if url set to decide if prod or dev/testing.

I think I should be able to define the local database with URL notation.
And that this case statement should be changed to check for something different.
What do you think?

**Comment by nicanor** [comment]
Another option is to define init like this:
```
  def init(_type, config) do
    if Application.get_env(:my_app, :environment) == :prod do
      Fly.Postgres.config_repo_url(config)
    else
      {:ok, config}
    end
  end
```

**Comment by brainlid** [comment]
Using the repo URL makes sense. Yes, for local dev I was taking a short-cut of assuming no DB URL form. Let me give that some more thought.

Thanks for the follow-up and additional info!

**Comment by brainlid** [comment]
I pushed the release v0.2.4 that should address this for you.

It introduces a breaking change. The README was updated, but [the PR contains more details](https://github.com/superfly/fly_postgres_elixir/pull/24).

Please check it out and let me know how it works for you. 

Also, if you want to have more control over when it tries to perform the DB URL rewriting, you can modify the `init` function to use your own special logic. It just needs to pass in a `:prod` when it should modify the URL.

**Comment by nicanor** [comment]
Thanks! That change will do.
