### ISSUE TITLE
Replication with SQLite and litestream

### ISSUE THREAD

**Issue by SebastianSzturo** [superfly/fly_postgres_elixir#25]
Can we get the same approach for SQLite with litestream read-only replicas and Phoenix? That would be a gamechanger!

**Comment by brainlid** [comment]
Hi @SebastianSzturo!

That sounds like an interesting idea and possibly something we might look into. I know there's currently interest in SQLite and multi-region. However, that isn't an issue for _this_ repo. :slightly_smiling_face:
