### ISSUE TITLE
 Lib crashes on startup without `base_name` option provided in childspec

### ISSUE THREAD

**Issue by rkachowski** [superfly/fly_postgres_elixir#33]
Due to this change - https://github.com/superfly/fly_postgres_elixir/blob/main/lib/lsn/lsn_tracker.ex#L53 the Fly.Postgres.LSN.Tracker process now requires a `base_name` parameter on startup as there is no default value. Without this provided, the application referencing the library will fail to start up.

# Expected result

* App starts up when following the instructions at https://github.com/superfly/fly_postgres_elixir/blame/main/README.md#L197
    * The readme references the required name
    * Or there's a default name for a single tracker instance

# Error logs

```
16:44:43.747 [notice] Application App exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Fly.Postgres.LSN.Tracker
    ** (EXIT) an exception was raised:
        ** (KeyError) key :base_name not found in: [repo: App.Repo.Local]
            (elixir 1.13.4) lib/keyword.ex:559: Keyword.fetch!/2
            (fly_postgres 0.3.0) lib/lsn/lsn_tracker.ex:53: Fly.Postgres.LSN.Tracker.start_link/1
            (stdlib 3.17.2) supervisor.erl:414: :supervisor.do_start_child_i/3
            (stdlib 3.17.2) supervisor.erl:400: :supervisor.do_start_child/2
            (stdlib 3.17.2) supervisor.erl:384: anonymous fn/3 in :supervisor.start_children/2
            (stdlib 3.17.2) supervisor.erl:1250: :supervisor.children_map/4
            (stdlib 3.17.2) supervisor.erl:350: :supervisor.init_children/2
            (stdlib 3.17.2) gen_server.erl:423: :gen_server.init_it/2
```

**Comment by brainlid** [comment]
Hi @rkachowski,

Thank you for the report! I think a migration guide would have been helpful to point out the changes. In your project's `application.ex` file, it changed to create a supervisor instead of the GenServer itself. The Supervisor handles the creation of the LSN Tracker.

```elixir
{Fly.Postgres.LSN.Supervisor, repo: MyApp.Repo.Local},
```

Note it is now a `Supervisor` being used.

**Comment by rkachowski** [comment]
Ah yes I overlooked this in my haste to upgrade - after changing to use the supervisor instead of the tracker directly, everything works smoothly. Thanks for your response.

**Comment by brainlid** [comment]
I believe this was from an issue migrating to v0.3.0. Please re-open if it is still an issue.
