### ISSUE TITLE
One more warning to be fixed

### ISSUE THREAD

**Issue by nicanor** [superfly/fly_postgres_elixir#40]
Hi!
I found one more line to be changed (from **Fly.rpc_primary** to **Fly.RPC.rpc_primary**)

https://github.com/superfly/fly_postgres_elixir/blob/91d152b7e40abe0ba22c448b84ee2af174984079/lib/repo.ex#L398C16-L398C16

I found it because I updated and I'm getting this warning.
```
warning: Fly.rpc_primary/4 is undefined (module Fly is not available or is yet to be defined)
  lib/brandkit/repo.ex:54: Brandkit.Repo.__exec_on_primary__/3
```

Thank you so much!

**Comment by f0rest8** [comment]
Seeing the same warning on update

**Comment by brainlid** [comment]
Thanks for the report @nicanor! It should be fixed now. I got a personal app updated and deployed with it as well. Let me know if you have any more issues!
